<?php

namespace Database\Seeders;

use App\Common\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->getCountriesArray() as $item) {
            Country::firstOrCreate([
                'code_alpha_2' => $item['code_alpha_2'],
                'code_alpha_3' => $item['code_alpha_3'],
                'code_numeric' => $item['code_numeric'],
                'name' => $item['name'],
            ]);
        }
    }

    private function getCountriesArray(): array
    {
        return [
            [
                'code_alpha_2' => 'AD',
                'code_alpha_3' => 'AND',
                'code_numeric' => '20',
                'name' => 'Andorra',
            ],
            [
                'code_alpha_2' => 'AF',
                'code_alpha_3' => 'AFG',
                'code_numeric' => '4',
                'name' => 'Afghanistan',
            ],
            [
                'code_alpha_2' => 'AE',
                'code_alpha_3' => 'ARE',
                'code_numeric' => '784',
                'name' => 'United Arab Emirates',
            ],
            [
                'code_alpha_2' => 'AX',
                'code_alpha_3' => 'ALA',
                'code_numeric' => '248',
                'name' => 'Åland Islands',
            ],
            [
                'code_alpha_2' => 'AL',
                'code_alpha_3' => 'ALB',
                'code_numeric' => '8',
                'name' => 'Albania',
            ],
            [
                'code_alpha_2' => 'AG',
                'code_alpha_3' => 'ATG',
                'code_numeric' => '28',
                'name' => 'Antigua and Barbuda',
            ],
            [
                'code_alpha_2' => 'DZ',
                'code_alpha_3' => 'DZA',
                'code_numeric' => '12',
                'name' => 'Algeria',
            ],
            [
                'code_alpha_2' => 'AI',
                'code_alpha_3' => 'AIA',
                'code_numeric' => '660',
                'name' => 'Anguilla',
            ],
            [
                'code_alpha_2' => 'AS',
                'code_alpha_3' => 'ASM',
                'code_numeric' => '16',
                'name' => 'American Samoa',
            ],
            [
                'code_alpha_2' => 'AM',
                'code_alpha_3' => 'ARM',
                'code_numeric' => '51',
                'name' => 'Armenia',
            ],
            [
                'code_alpha_2' => 'AO',
                'code_alpha_3' => 'AGO',
                'code_numeric' => '24',
                'name' => 'Angola',
            ],
            [
                'code_alpha_2' => 'AQ',
                'code_alpha_3' => 'ATA',
                'code_numeric' => '10',
                'name' => 'Antarctica',
            ],
            [
                'code_alpha_2' => 'AR',
                'code_alpha_3' => 'ARG',
                'code_numeric' => '32',
                'name' => 'Argentina',
            ],
            [
                'code_alpha_2' => 'AT',
                'code_alpha_3' => 'AUT',
                'code_numeric' => '40',
                'name' => 'Austria',
            ],
            [
                'code_alpha_2' => 'AU',
                'code_alpha_3' => 'AUS',
                'code_numeric' => '36',
                'name' => 'Australia',
            ],
            [
                'code_alpha_2' => 'AW',
                'code_alpha_3' => 'ABW',
                'code_numeric' => '533',
                'name' => 'Aruba',
            ],
            [
                'code_alpha_2' => 'AZ',
                'code_alpha_3' => 'AZE',
                'code_numeric' => '31',
                'name' => 'Azerbaijan',
            ],
            [
                'code_alpha_2' => 'BA',
                'code_alpha_3' => 'BIH',
                'code_numeric' => '70',
                'name' => 'Bosnia and Herzegovina',
            ],
            [
                'code_alpha_2' => 'BS',
                'code_alpha_3' => 'BHS',
                'code_numeric' => '44',
                'name' => 'Bahamas',
            ],
            [
                'code_alpha_2' => 'BB',
                'code_alpha_3' => 'BRB',
                'code_numeric' => '52',
                'name' => 'Barbados',
            ],
            [
                'code_alpha_2' => 'BH',
                'code_alpha_3' => 'BHR',
                'code_numeric' => '48',
                'name' => 'Bahrain',
            ],
            [
                'code_alpha_2' => 'BD',
                'code_alpha_3' => 'BGD',
                'code_numeric' => '50',
                'name' => 'Bangladesh',
            ],
            [
                'code_alpha_2' => 'BE',
                'code_alpha_3' => 'BEL',
                'code_numeric' => '56',
                'name' => 'Belgium',
            ],
            [
                'code_alpha_2' => 'BF',
                'code_alpha_3' => 'BFA',
                'code_numeric' => '854',
                'name' => 'Burkina Faso',
            ],
            [
                'code_alpha_2' => 'BY',
                'code_alpha_3' => 'BLR',
                'code_numeric' => '112',
                'name' => 'Belarus',
            ],
            [
                'code_alpha_2' => 'BG',
                'code_alpha_3' => 'BGR',
                'code_numeric' => '100',
                'name' => 'Bulgaria',
            ],
            [
                'code_alpha_2' => 'BZ',
                'code_alpha_3' => 'BLZ',
                'code_numeric' => '84',
                'name' => 'Belize',
            ],
            [
                'code_alpha_2' => 'BI',
                'code_alpha_3' => 'BDI',
                'code_numeric' => '108',
                'name' => 'Burundi',
            ],
            [
                'code_alpha_2' => 'BJ',
                'code_alpha_3' => 'BEN',
                'code_numeric' => '204',
                'name' => 'Benin',
            ],
            [
                'code_alpha_2' => 'BM',
                'code_alpha_3' => 'BMU',
                'code_numeric' => '60',
                'name' => 'Bermuda',
            ],
            [
                'code_alpha_2' => 'BL',
                'code_alpha_3' => 'BLM',
                'code_numeric' => '652',
                'name' => 'Saint Barthélemy',
            ],
            [
                'code_alpha_2' => 'BT',
                'code_alpha_3' => 'BTN',
                'code_numeric' => '64',
                'name' => 'Bhutan',
            ],
            [
                'code_alpha_2' => 'BO',
                'code_alpha_3' => 'BOL',
                'code_numeric' => '68',
                'name' => 'Bolivia',
            ],
            [
                'code_alpha_2' => 'BN',
                'code_alpha_3' => 'BRN',
                'code_numeric' => '96',
                'name' => 'Brunei Darussalam',
            ],
            [
                'code_alpha_2' => 'BQ',
                'code_alpha_3' => 'BES',
                'code_numeric' => '535',
                'name' => 'Bonaire, Sint Eustatius, Saba',
            ],
            [
                'code_alpha_2' => 'BW',
                'code_alpha_3' => 'BWA',
                'code_numeric' => '72',
                'name' => 'Botswana',
            ],
            [
                'code_alpha_2' => 'BR',
                'code_alpha_3' => 'BRA',
                'code_numeric' => '76',
                'name' => 'Brazil',
            ],
            [
                'code_alpha_2' => 'BV',
                'code_alpha_3' => 'BVT',
                'code_numeric' => '74',
                'name' => 'Bouvet Island',
            ],
            [
                'code_alpha_2' => 'IO',
                'code_alpha_3' => 'IOT',
                'code_numeric' => '86',
                'name' => 'British Indian Ocean Territory',
            ],
            [
                'code_alpha_2' => 'CA',
                'code_alpha_3' => 'CAN',
                'code_numeric' => '124',
                'name' => 'Canada',
            ],
            [
                'code_alpha_2' => 'KH',
                'code_alpha_3' => 'KHM',
                'code_numeric' => '116',
                'name' => 'Cambodia',
            ],
            [
                'code_alpha_2' => 'CC',
                'code_alpha_3' => 'CCK',
                'code_numeric' => '166',
                'name' => 'Cocos Islands',
            ],
            [
                'code_alpha_2' => 'CM',
                'code_alpha_3' => 'CMR',
                'code_numeric' => '120',
                'name' => 'Cameroon',
            ],
            [
                'code_alpha_2' => 'CD',
                'code_alpha_3' => 'COD',
                'code_numeric' => '180',
                'name' => 'Democratic Republic of the Congo',
            ],
            [
                'code_alpha_2' => 'CF',
                'code_alpha_3' => 'CAF',
                'code_numeric' => '140',
                'name' => 'Central African Republic',
            ],
            [
                'code_alpha_2' => 'CV',
                'code_alpha_3' => 'CPV',
                'code_numeric' => '132',
                'name' => 'Cabo Verde',
            ],
            [
                'code_alpha_2' => 'CG',
                'code_alpha_3' => 'COG',
                'code_numeric' => '178',
                'name' => 'Congo',
            ],
            [
                'code_alpha_2' => 'KY',
                'code_alpha_3' => 'CYM',
                'code_numeric' => '136',
                'name' => 'Cayman Islands',
            ],
            [
                'code_alpha_2' => 'CH',
                'code_alpha_3' => 'CHE',
                'code_numeric' => '756',
                'name' => 'Switzerland',
            ],
            [
                'code_alpha_2' => 'CI',
                'code_alpha_3' => 'CIV',
                'code_numeric' => '384',
                'name' => 'Côte d\'Ivoire',
            ],
            [
                'code_alpha_2' => 'TD',
                'code_alpha_3' => 'TCD',
                'code_numeric' => '148',
                'name' => 'Chad',
            ],
            [
                'code_alpha_2' => 'CK',
                'code_alpha_3' => 'COK',
                'code_numeric' => '184',
                'name' => 'Cook Islands',
            ],
            [
                'code_alpha_2' => 'CL',
                'code_alpha_3' => 'CHL',
                'code_numeric' => '152',
                'name' => 'Chile',
            ],
            [
                'code_alpha_2' => 'CN',
                'code_alpha_3' => 'CHN',
                'code_numeric' => '156',
                'name' => 'China',
            ],
            [
                'code_alpha_2' => 'CX',
                'code_alpha_3' => 'CXR',
                'code_numeric' => '162',
                'name' => 'Christmas Island',
            ],
            [
                'code_alpha_2' => 'CO',
                'code_alpha_3' => 'COL',
                'code_numeric' => '170',
                'name' => 'Colombia',
            ],
            [
                'code_alpha_2' => 'CR',
                'code_alpha_3' => 'CRI',
                'code_numeric' => '188',
                'name' => 'Costa Rica',
            ],
            [
                'code_alpha_2' => 'KM',
                'code_alpha_3' => 'COM',
                'code_numeric' => '174',
                'name' => 'Comoros',
            ],
            [
                'code_alpha_2' => 'CU',
                'code_alpha_3' => 'CUB',
                'code_numeric' => '192',
                'name' => 'Cuba',
            ],
            [
                'code_alpha_2' => 'CW',
                'code_alpha_3' => 'CUW',
                'code_numeric' => '531',
                'name' => 'Curaçao',
            ],
            [
                'code_alpha_2' => 'CY',
                'code_alpha_3' => 'CYP',
                'code_numeric' => '196',
                'name' => 'Cyprus',
            ],
            [
                'code_alpha_2' => 'CZ',
                'code_alpha_3' => 'CZE',
                'code_numeric' => '203',
                'name' => 'Czechia',
            ],
            [
                'code_alpha_2' => 'HR',
                'code_alpha_3' => 'HRV',
                'code_numeric' => '191',
                'name' => 'Croatia',
            ],
            [
                'code_alpha_2' => 'DE',
                'code_alpha_3' => 'DEU',
                'code_numeric' => '276',
                'name' => 'Germany',
            ],
            [
                'code_alpha_2' => 'DJ',
                'code_alpha_3' => 'DJI',
                'code_numeric' => '262',
                'name' => 'Djibouti',
            ],
            [
                'code_alpha_2' => 'DK',
                'code_alpha_3' => 'DNK',
                'code_numeric' => '208',
                'name' => 'Denmark',
            ],
            [
                'code_alpha_2' => 'DM',
                'code_alpha_3' => 'DMA',
                'code_numeric' => '212',
                'name' => 'Dominica',
            ],
            [
                'code_alpha_2' => 'DO',
                'code_alpha_3' => 'DOM',
                'code_numeric' => '214',
                'name' => 'Dominican Republic',
            ],
            [
                'code_alpha_2' => 'EC',
                'code_alpha_3' => 'ECU',
                'code_numeric' => '218',
                'name' => 'Ecuador',
            ],
            [
                'code_alpha_2' => 'EE',
                'code_alpha_3' => 'EST',
                'code_numeric' => '233',
                'name' => 'Estonia',
            ],
            [
                'code_alpha_2' => 'EG',
                'code_alpha_3' => 'EGY',
                'code_numeric' => '818',
                'name' => 'Egypt',
            ],
            [
                'code_alpha_2' => 'EH',
                'code_alpha_3' => 'ESH',
                'code_numeric' => '732',
                'name' => 'Western Sahara',
            ],
            [
                'code_alpha_2' => 'ER',
                'code_alpha_3' => 'ERI',
                'code_numeric' => '232',
                'name' => 'Eritrea',
            ],
            [
                'code_alpha_2' => 'SV',
                'code_alpha_3' => 'SLV',
                'code_numeric' => '222',
                'name' => 'El Salvador',
            ],
            [
                'code_alpha_2' => 'ES',
                'code_alpha_3' => 'ESP',
                'code_numeric' => '724',
                'name' => 'Spain',
            ],
            [
                'code_alpha_2' => 'GQ',
                'code_alpha_3' => 'GNQ',
                'code_numeric' => '226',
                'name' => 'Equatorial Guinea',
            ],
            [
                'code_alpha_2' => 'ET',
                'code_alpha_3' => 'ETH',
                'code_numeric' => '231',
                'name' => 'Ethiopia',
            ],
            [
                'code_alpha_2' => 'FI',
                'code_alpha_3' => 'FIN',
                'code_numeric' => '246',
                'name' => 'Finland',
            ],
            [
                'code_alpha_2' => 'FJ',
                'code_alpha_3' => 'FJI',
                'code_numeric' => '242',
                'name' => 'Fiji',
            ],
            [
                'code_alpha_2' => 'FK',
                'code_alpha_3' => 'FLK',
                'code_numeric' => '238',
                'name' => 'Falkland Islands',
            ],
            [
                'code_alpha_2' => 'FM',
                'code_alpha_3' => 'FSM',
                'code_numeric' => '583',
                'name' => 'Micronesia',
            ],
            [
                'code_alpha_2' => 'FO',
                'code_alpha_3' => 'FRO',
                'code_numeric' => '234',
                'name' => 'Faroe Islands',
            ],
            [
                'code_alpha_2' => 'FR',
                'code_alpha_3' => 'FRA',
                'code_numeric' => '250',
                'name' => 'France',
            ],
            [
                'code_alpha_2' => 'GA',
                'code_alpha_3' => 'GAB',
                'code_numeric' => '266',
                'name' => 'Gabon',
            ],
            [
                'code_alpha_2' => 'GB',
                'code_alpha_3' => 'GBR',
                'code_numeric' => '826',
                'name' => 'United Kingdom of Great Britain and Northern Ireland',
            ],
            [
                'code_alpha_2' => 'GF',
                'code_alpha_3' => 'GUF',
                'code_numeric' => '254',
                'name' => 'French Guiana',
            ],
            [
                'code_alpha_2' => 'GD',
                'code_alpha_3' => 'GRD',
                'code_numeric' => '308',
                'name' => 'Grenada',
            ],
            [
                'code_alpha_2' => 'PF',
                'code_alpha_3' => 'PYF',
                'code_numeric' => '258',
                'name' => 'French Polynesia',
            ],
            [
                'code_alpha_2' => 'GE',
                'code_alpha_3' => 'GEO',
                'code_numeric' => '268',
                'name' => 'Georgia',
            ],
            [
                'code_alpha_2' => 'TF',
                'code_alpha_3' => 'ATF',
                'code_numeric' => '260',
                'name' => 'French Southern Territories',
            ],
            [
                'code_alpha_2' => 'GG',
                'code_alpha_3' => 'GGY',
                'code_numeric' => '831',
                'name' => 'Guernsey',
            ],
            [
                'code_alpha_2' => 'GM',
                'code_alpha_3' => 'GMB',
                'code_numeric' => '270',
                'name' => 'Gambia',
            ],
            [
                'code_alpha_2' => 'GH',
                'code_alpha_3' => 'GHA',
                'code_numeric' => '288',
                'name' => 'Ghana',
            ],
            [
                'code_alpha_2' => 'GI',
                'code_alpha_3' => 'GIB',
                'code_numeric' => '292',
                'name' => 'Gibraltar',
            ],
            [
                'code_alpha_2' => 'GL',
                'code_alpha_3' => 'GRL',
                'code_numeric' => '304',
                'name' => 'Greenland',
            ],
            [
                'code_alpha_2' => 'GN',
                'code_alpha_3' => 'GIN',
                'code_numeric' => '324',
                'name' => 'Guinea',
            ],
            [
                'code_alpha_2' => 'GR',
                'code_alpha_3' => 'GRC',
                'code_numeric' => '300',
                'name' => 'Greece',
            ],
            [
                'code_alpha_2' => 'GP',
                'code_alpha_3' => 'GLP',
                'code_numeric' => '312',
                'name' => 'Guadeloupe',
            ],
            [
                'code_alpha_2' => 'GS',
                'code_alpha_3' => 'SGS',
                'code_numeric' => '239',
                'name' => 'South Georgia and the South Sandwich Islands',
            ],
            [
                'code_alpha_2' => 'GU',
                'code_alpha_3' => 'GUM',
                'code_numeric' => '316',
                'name' => 'Guam',
            ],
            [
                'code_alpha_2' => 'GT',
                'code_alpha_3' => 'GTM',
                'code_numeric' => '320',
                'name' => 'Guatemala',
            ],
            [
                'code_alpha_2' => 'GW',
                'code_alpha_3' => 'GNB',
                'code_numeric' => '624',
                'name' => 'Guinea - Bissau',
            ],
            [
                'code_alpha_2' => 'GY',
                'code_alpha_3' => 'GUY',
                'code_numeric' => '328',
                'name' => 'Guyana',
            ],
            [
                'code_alpha_2' => 'HK',
                'code_alpha_3' => 'HKG',
                'code_numeric' => '344',
                'name' => 'Hong Kong',
            ],
            [
                'code_alpha_2' => 'HM',
                'code_alpha_3' => 'HMD',
                'code_numeric' => '334',
                'name' => 'Heard Island and McDonald Islands',
            ],
            [
                'code_alpha_2' => 'HT',
                'code_alpha_3' => 'HTI',
                'code_numeric' => '332',
                'name' => 'Haiti',
            ],
            [
                'code_alpha_2' => 'HN',
                'code_alpha_3' => 'HND',
                'code_numeric' => '340',
                'name' => 'Honduras',
            ],
            [
                'code_alpha_2' => 'VA',
                'code_alpha_3' => 'VAT',
                'code_numeric' => '336',
                'name' => 'Holy See',
            ],
            [
                'code_alpha_2' => 'HU',
                'code_alpha_3' => 'HUN',
                'code_numeric' => '348',
                'name' => 'Hungary',
            ],
            [
                'code_alpha_2' => 'ID',
                'code_alpha_3' => 'IDN',
                'code_numeric' => '360',
                'name' => 'Indonesia',
            ],
            [
                'code_alpha_2' => 'IE',
                'code_alpha_3' => 'IRL',
                'code_numeric' => '372',
                'name' => 'Ireland',
            ],
            [
                'code_alpha_2' => 'IS',
                'code_alpha_3' => 'ISL',
                'code_numeric' => '352',
                'name' => 'Iceland',
            ],
            [
                'code_alpha_2' => 'IL',
                'code_alpha_3' => 'ISR',
                'code_numeric' => '376',
                'name' => 'Israel',
            ],
            [
                'code_alpha_2' => 'IN',
                'code_alpha_3' => 'IND',
                'code_numeric' => '356',
                'name' => 'India',
            ],
            [
                'code_alpha_2' => 'IM',
                'code_alpha_3' => 'IMN',
                'code_numeric' => '833',
                'name' => 'Isle of Man',
            ],
            [
                'code_alpha_2' => 'IR',
                'code_alpha_3' => 'IRN',
                'code_numeric' => '364',
                'name' => 'Iran',
            ],
            [
                'code_alpha_2' => 'IQ',
                'code_alpha_3' => 'IRQ',
                'code_numeric' => '368',
                'name' => 'Iraq',
            ],
            [
                'code_alpha_2' => 'IT',
                'code_alpha_3' => 'ITA',
                'code_numeric' => '380',
                'name' => 'Italy',
            ],
            [
                'code_alpha_2' => 'JE',
                'code_alpha_3' => 'JEY',
                'code_numeric' => '832',
                'name' => 'Jersey',
            ],
            [
                'code_alpha_2' => 'JM',
                'code_alpha_3' => 'JAM',
                'code_numeric' => '388',
                'name' => 'Jamaica',
            ],
            [
                'code_alpha_2' => 'JP',
                'code_alpha_3' => 'JPN',
                'code_numeric' => '392',
                'name' => 'Japan',
            ],
            [
                'code_alpha_2' => 'JO',
                'code_alpha_3' => 'JOR',
                'code_numeric' => '400',
                'name' => 'Jordan',
            ],
            [
                'code_alpha_2' => 'KE',
                'code_alpha_3' => 'KEN',
                'code_numeric' => '404',
                'name' => 'Kenya',
            ],
            [
                'code_alpha_2' => 'KZ',
                'code_alpha_3' => 'KAZ',
                'code_numeric' => '398',
                'name' => 'Kazakhstan',
            ],
            [
                'code_alpha_2' => 'KG',
                'code_alpha_3' => 'KGZ',
                'code_numeric' => '417',
                'name' => 'Kyrgyzstan',
            ],
            [
                'code_alpha_2' => 'KI',
                'code_alpha_3' => 'KIR',
                'code_numeric' => '296',
                'name' => 'Kiribati',
            ],
            [
                'code_alpha_2' => 'KP',
                'code_alpha_3' => 'PRK',
                'code_numeric' => '408',
                'name' => 'Democratic People\'s Republic of Korea',
            ],
            [
                'code_alpha_2' => 'KR',
                'code_alpha_3' => 'KOR',
                'code_numeric' => '410',
                'name' => 'Korea',
            ],
            [
                'code_alpha_2' => 'KN',
                'code_alpha_3' => 'KNA',
                'code_numeric' => '659',
                'name' => 'Saint Kitts and Nevis',
            ],
            [
                'code_alpha_2' => 'KW',
                'code_alpha_3' => 'KWT',
                'code_numeric' => '414',
                'name' => 'Kuwait',
            ],
            [
                'code_alpha_2' => 'LA',
                'code_alpha_3' => 'LAO',
                'code_numeric' => '418',
                'name' => 'Lao People\'s Democratic Republic',
            ],
            [
                'code_alpha_2' => 'LV',
                'code_alpha_3' => 'LVA',
                'code_numeric' => '428',
                'name' => 'Latvia',
            ],
            [
                'code_alpha_2' => 'LB',
                'code_alpha_3' => 'LBN',
                'code_numeric' => '422',
                'name' => 'Lebanon',
            ],
            [
                'code_alpha_2' => 'LS',
                'code_alpha_3' => 'LSO',
                'code_numeric' => '426',
                'name' => 'Lesotho',
            ],
            [
                'code_alpha_2' => 'LR',
                'code_alpha_3' => 'LBR',
                'code_numeric' => '430',
                'name' => 'Liberia',
            ],
            [
                'code_alpha_2' => 'LY',
                'code_alpha_3' => 'LBY',
                'code_numeric' => '434',
                'name' => 'Libya',
            ],
            [
                'code_alpha_2' => 'LC',
                'code_alpha_3' => 'LCA',
                'code_numeric' => '662',
                'name' => 'Saint Lucia',
            ],
            [
                'code_alpha_2' => 'LI',
                'code_alpha_3' => 'LIE',
                'code_numeric' => '438',
                'name' => 'Liechtenstein',
            ],
            [
                'code_alpha_2' => 'LT',
                'code_alpha_3' => 'LTU',
                'code_numeric' => '440',
                'name' => 'Lithuania',
            ],
            [
                'code_alpha_2' => 'LK',
                'code_alpha_3' => 'LKA',
                'code_numeric' => '144',
                'name' => 'Sri Lanka',
            ],
            [
                'code_alpha_2' => 'LU',
                'code_alpha_3' => 'LUX',
                'code_numeric' => '442',
                'name' => 'Luxembourg',
            ],
            [
                'code_alpha_2' => 'MO',
                'code_alpha_3' => 'MAC',
                'code_numeric' => '446',
                'name' => 'Macao',
            ],
            [
                'code_alpha_2' => 'MK',
                'code_alpha_3' => 'MKD',
                'code_numeric' => '807',
                'name' => 'North Macedonia',
            ],
            [
                'code_alpha_2' => 'MG',
                'code_alpha_3' => 'MDG',
                'code_numeric' => '450',
                'name' => 'Madagascar',
            ],
            [
                'code_alpha_2' => 'MW',
                'code_alpha_3' => 'MWI',
                'code_numeric' => '454',
                'name' => 'Malawi',
            ],
            [
                'code_alpha_2' => 'MY',
                'code_alpha_3' => 'MYS',
                'code_numeric' => '458',
                'name' => 'Malaysia',
            ],
            [
                'code_alpha_2' => 'MV',
                'code_alpha_3' => 'MDV',
                'code_numeric' => '462',
                'name' => 'Maldives',
            ],
            [
                'code_alpha_2' => 'MA',
                'code_alpha_3' => 'MAR',
                'code_numeric' => '504',
                'name' => 'Morocco',
            ],
            [
                'code_alpha_2' => 'ML',
                'code_alpha_3' => 'MLI',
                'code_numeric' => '466',
                'name' => 'Mali',
            ],
            [
                'code_alpha_2' => 'MC',
                'code_alpha_3' => 'MCO',
                'code_numeric' => '492',
                'name' => 'Monaco',
            ],
            [
                'code_alpha_2' => 'MT',
                'code_alpha_3' => 'MLT',
                'code_numeric' => '470',
                'name' => 'Malta',
            ],
            [
                'code_alpha_2' => 'MD',
                'code_alpha_3' => 'MDA',
                'code_numeric' => '498',
                'name' => 'Moldova',
            ],
            [
                'code_alpha_2' => 'MH',
                'code_alpha_3' => 'MHL',
                'code_numeric' => '584',
                'name' => 'Marshall Islands',
            ],
            [
                'code_alpha_2' => 'ME',
                'code_alpha_3' => 'MNE',
                'code_numeric' => '499',
                'name' => 'Montenegro',
            ],
            [
                'code_alpha_2' => 'MQ',
                'code_alpha_3' => 'MTQ',
                'code_numeric' => '474',
                'name' => 'Martinique',
            ],
            [
                'code_alpha_2' => 'MF',
                'code_alpha_3' => 'MAF',
                'code_numeric' => '663',
                'name' => 'Saint Martin',
            ],
            [
                'code_alpha_2' => 'MR',
                'code_alpha_3' => 'MRT',
                'code_numeric' => '478',
                'name' => 'Mauritania',
            ],
            [
                'code_alpha_2' => 'MU',
                'code_alpha_3' => 'MUS',
                'code_numeric' => '480',
                'name' => 'Mauritius',
            ],
            [
                'code_alpha_2' => 'YT',
                'code_alpha_3' => 'MYT',
                'code_numeric' => '175',
                'name' => 'Mayotte',
            ],
            [
                'code_alpha_2' => 'MX',
                'code_alpha_3' => 'MEX',
                'code_numeric' => '484',
                'name' => 'Mexico',
            ],
            [
                'code_alpha_2' => 'MM',
                'code_alpha_3' => 'MMR',
                'code_numeric' => '104',
                'name' => 'Myanmar',
            ],
            [
                'code_alpha_2' => 'MN',
                'code_alpha_3' => 'MNG',
                'code_numeric' => '496',
                'name' => 'Mongolia',
            ],
            [
                'code_alpha_2' => 'MP',
                'code_alpha_3' => 'MNP',
                'code_numeric' => '580',
                'name' => 'Northern Mariana Islands',
            ],
            [
                'code_alpha_2' => 'MS',
                'code_alpha_3' => 'MSR',
                'code_numeric' => '500',
                'name' => 'Montserrat',
            ],
            [
                'code_alpha_2' => 'MZ',
                'code_alpha_3' => 'MOZ',
                'code_numeric' => '508',
                'name' => 'Mozambique',
            ],
            [
                'code_alpha_2' => 'NA',
                'code_alpha_3' => 'NAM',
                'code_numeric' => '516',
                'name' => 'Namibia',
            ],
            [
                'code_alpha_2' => 'NR',
                'code_alpha_3' => 'NRU',
                'code_numeric' => '520',
                'name' => 'Nauru',
            ],
            [
                'code_alpha_2' => 'NP',
                'code_alpha_3' => 'NPL',
                'code_numeric' => '524',
                'name' => 'Nepal',
            ],
            [
                'code_alpha_2' => 'NL',
                'code_alpha_3' => 'NLD',
                'code_numeric' => '528',
                'name' => 'Netherlands',
            ],
            [
                'code_alpha_2' => 'NC',
                'code_alpha_3' => 'NCL',
                'code_numeric' => '540',
                'name' => 'New Caledonia',
            ],
            [
                'code_alpha_2' => 'NZ',
                'code_alpha_3' => 'NZL',
                'code_numeric' => '554',
                'name' => 'New Zealand',
            ],
            [
                'code_alpha_2' => 'NI',
                'code_alpha_3' => 'NIC',
                'code_numeric' => '558',
                'name' => 'Nicaragua',
            ],
            [
                'code_alpha_2' => 'NE',
                'code_alpha_3' => 'NER',
                'code_numeric' => '562',
                'name' => 'Niger',
            ],
            [
                'code_alpha_2' => 'NG',
                'code_alpha_3' => 'NGA',
                'code_numeric' => '566',
                'name' => 'Nigeria',
            ],
            [
                'code_alpha_2' => 'NF',
                'code_alpha_3' => 'NFK',
                'code_numeric' => '574',
                'name' => 'Norfolk Island',
            ],
            [
                'code_alpha_2' => 'NU',
                'code_alpha_3' => 'NIU',
                'code_numeric' => '570',
                'name' => 'Niue',
            ],
            [
                'code_alpha_2' => 'NO',
                'code_alpha_3' => 'NOR',
                'code_numeric' => '578',
                'name' => 'Norway',
            ],
            [
                'code_alpha_2' => 'OM',
                'code_alpha_3' => 'OMN',
                'code_numeric' => '512',
                'name' => 'Oman',
            ],
            [
                'code_alpha_2' => 'PK',
                'code_alpha_3' => 'PAK',
                'code_numeric' => '586',
                'name' => 'Pakistan',
            ],
            [
                'code_alpha_2' => 'PW',
                'code_alpha_3' => 'PLW',
                'code_numeric' => '585',
                'name' => 'Palau',
            ],
            [
                'code_alpha_2' => 'PS',
                'code_alpha_3' => 'PSE',
                'code_numeric' => '275',
                'name' => 'Palestine',
            ],
            [
                'code_alpha_2' => 'PA',
                'code_alpha_3' => 'PAN',
                'code_numeric' => '591',
                'name' => 'Panama',
            ],
            [
                'code_alpha_2' => 'PG',
                'code_alpha_3' => 'PNG',
                'code_numeric' => '598',
                'name' => 'Papua New Guinea',
            ],
            [
                'code_alpha_2' => 'PY',
                'code_alpha_3' => 'PRY',
                'code_numeric' => '600',
                'name' => 'Paraguay',
            ],
            [
                'code_alpha_2' => 'PE',
                'code_alpha_3' => 'PER',
                'code_numeric' => '604',
                'name' => 'Peru',
            ],
            [
                'code_alpha_2' => 'PH',
                'code_alpha_3' => 'PHL',
                'code_numeric' => '608',
                'name' => 'Philippines',
            ],
            [
                'code_alpha_2' => 'PN',
                'code_alpha_3' => 'PCN',
                'code_numeric' => '612',
                'name' => 'Pitcairn',
            ],
            [
                'code_alpha_2' => 'PL',
                'code_alpha_3' => 'POL',
                'code_numeric' => '616',
                'name' => 'Poland',
            ],
            [
                'code_alpha_2' => 'PT',
                'code_alpha_3' => 'PRT',
                'code_numeric' => '620',
                'name' => 'Portugal',
            ],
            [
                'code_alpha_2' => 'PR',
                'code_alpha_3' => 'PRI',
                'code_numeric' => '630',
                'name' => 'Puerto Rico',
            ],
            [
                'code_alpha_2' => 'PM',
                'code_alpha_3' => 'SPM',
                'code_numeric' => '666',
                'name' => 'Saint Pierre and Miquelon',
            ],
            [
                'code_alpha_2' => 'QA',
                'code_alpha_3' => 'QAT',
                'code_numeric' => '634',
                'name' => 'Qatar',
            ],
            [
                'code_alpha_2' => 'RE',
                'code_alpha_3' => 'REU',
                'code_numeric' => '638',
                'name' => 'Réunion',
            ],
            [
                'code_alpha_2' => 'RO',
                'code_alpha_3' => 'ROU',
                'code_numeric' => '642',
                'name' => 'Romania',
            ],
            [
                'code_alpha_2' => 'RU',
                'code_alpha_3' => 'RUS',
                'code_numeric' => '643',
                'name' => 'Russian Federation',
            ],
            [
                'code_alpha_2' => 'RW',
                'code_alpha_3' => 'RWA',
                'code_numeric' => '646',
                'name' => 'Rwanda',
            ],
            [
                'code_alpha_2' => 'SH',
                'code_alpha_3' => 'SHN',
                'code_numeric' => '654',
                'name' => 'Saint Helena, Ascension Island, Tristan da Cunha',
            ],
            [
                'code_alpha_2' => 'RS',
                'code_alpha_3' => 'SRB',
                'code_numeric' => '688',
                'name' => 'Serbia',
            ],
            [
                'code_alpha_2' => 'VC',
                'code_alpha_3' => 'VCT',
                'code_numeric' => '670',
                'name' => 'Saint Vincent and the Grenadines',
            ],
            [
                'code_alpha_2' => 'WS',
                'code_alpha_3' => 'WSM',
                'code_numeric' => '882',
                'name' => 'Samoa',
            ],
            [
                'code_alpha_2' => 'SA',
                'code_alpha_3' => 'SAU',
                'code_numeric' => '682',
                'name' => 'Saudi Arabia',
            ],
            [
                'code_alpha_2' => 'SM',
                'code_alpha_3' => 'SMR',
                'code_numeric' => '674',
                'name' => 'San Marino',
            ],
            [
                'code_alpha_2' => 'SB',
                'code_alpha_3' => 'SLB',
                'code_numeric' => '90',
                'name' => 'Solomon Islands',
            ],
            [
                'code_alpha_2' => 'ST',
                'code_alpha_3' => 'STP',
                'code_numeric' => '678',
                'name' => 'Sao Tome and Principe',
            ],
            [
                'code_alpha_2' => 'SC',
                'code_alpha_3' => 'SYC',
                'code_numeric' => '690',
                'name' => 'Seychelles',
            ],
            [
                'code_alpha_2' => 'SD',
                'code_alpha_3' => 'SDN',
                'code_numeric' => '729',
                'name' => 'Sudan',
            ],
            [
                'code_alpha_2' => 'SN',
                'code_alpha_3' => 'SEN',
                'code_numeric' => '686',
                'name' => 'Senegal',
            ],
            [
                'code_alpha_2' => 'SE',
                'code_alpha_3' => 'SWE',
                'code_numeric' => '752',
                'name' => 'Sweden',
            ],
            [
                'code_alpha_2' => 'SG',
                'code_alpha_3' => 'SGP',
                'code_numeric' => '702',
                'name' => 'Singapore',
            ],
            [
                'code_alpha_2' => 'SL',
                'code_alpha_3' => 'SLE',
                'code_numeric' => '694',
                'name' => 'Sierra Leone',
            ],
            [
                'code_alpha_2' => 'SI',
                'code_alpha_3' => 'SVN',
                'code_numeric' => '705',
                'name' => 'Slovenia',
            ],
            [
                'code_alpha_2' => 'SJ',
                'code_alpha_3' => 'SJM',
                'code_numeric' => '744',
                'name' => 'Svalbard, Jan Mayen',
            ],
            [
                'code_alpha_2' => 'SX',
                'code_alpha_3' => 'SXM',
                'code_numeric' => '534',
                'name' => 'Sint Maarten',
            ],
            [
                'code_alpha_2' => 'SK',
                'code_alpha_3' => 'SVK',
                'code_numeric' => '703',
                'name' => 'Slovakia',
            ],
            [
                'code_alpha_2' => 'SO',
                'code_alpha_3' => 'SOM',
                'code_numeric' => '706',
                'name' => 'Somalia',
            ],
            [
                'code_alpha_2' => 'ZA',
                'code_alpha_3' => 'ZAF',
                'code_numeric' => '710',
                'name' => 'South Africa',
            ],
            [
                'code_alpha_2' => 'SR',
                'code_alpha_3' => 'SUR',
                'code_numeric' => '740',
                'name' => 'Suriname',
            ],
            [
                'code_alpha_2' => 'SS',
                'code_alpha_3' => 'SSD',
                'code_numeric' => '728',
                'name' => 'South Sudan',
            ],
            [
                'code_alpha_2' => 'SY',
                'code_alpha_3' => 'SYR',
                'code_numeric' => '760',
                'name' => 'Syrian Arab Republic',
            ],
            [
                'code_alpha_2' => 'SZ',
                'code_alpha_3' => 'SWZ',
                'code_numeric' => '748',
                'name' => 'Eswatini',
            ],
            [
                'code_alpha_2' => 'TC',
                'code_alpha_3' => 'TCA',
                'code_numeric' => '796',
                'name' => 'Turks and Caicos Islands',
            ],
            [
                'code_alpha_2' => 'TG',
                'code_alpha_3' => 'TGO',
                'code_numeric' => '768',
                'name' => 'Togo',
            ],
            [
                'code_alpha_2' => 'TH',
                'code_alpha_3' => 'THA',
                'code_numeric' => '764',
                'name' => 'Thailand',
            ],
            [
                'code_alpha_2' => 'TW',
                'code_alpha_3' => 'TWN',
                'code_numeric' => '158',
                'name' => 'Taiwan',
            ],
            [
                'code_alpha_2' => 'TJ',
                'code_alpha_3' => 'TJK',
                'code_numeric' => '762',
                'name' => 'Tajikistan',
            ],
            [
                'code_alpha_2' => 'TK',
                'code_alpha_3' => 'TKL',
                'code_numeric' => '772',
                'name' => 'Tokelau',
            ],
            [
                'code_alpha_2' => 'TZ',
                'code_alpha_3' => 'TZA',
                'code_numeric' => '834',
                'name' => 'Tanzania',
            ],
            [
                'code_alpha_2' => 'TL',
                'code_alpha_3' => 'TLS',
                'code_numeric' => '626',
                'name' => 'Timor-Leste',
            ],
            [
                'code_alpha_2' => 'TM',
                'code_alpha_3' => 'TKM',
                'code_numeric' => '795',
                'name' => 'Turkmenistan',
            ],
            [
                'code_alpha_2' => 'TN',
                'code_alpha_3' => 'TUN',
                'code_numeric' => '788',
                'name' => 'Tunisia',
            ],
            [
                'code_alpha_2' => 'TO',
                'code_alpha_3' => 'TON',
                'code_numeric' => '776',
                'name' => 'Tonga',
            ],
            [
                'code_alpha_2' => 'TR',
                'code_alpha_3' => 'TUR',
                'code_numeric' => '792',
                'name' => 'Türkiye',
            ],
            [
                'code_alpha_2' => 'TT',
                'code_alpha_3' => 'TTO',
                'code_numeric' => '780',
                'name' => 'Trinidad and Tobago',
            ],
            [
                'code_alpha_2' => 'TV',
                'code_alpha_3' => 'TUV',
                'code_numeric' => '798',
                'name' => 'Tuvalu',
            ],
            [
                'code_alpha_2' => 'UA',
                'code_alpha_3' => 'UKR',
                'code_numeric' => '804',
                'name' => 'Ukraine',
            ],
            [
                'code_alpha_2' => 'UG',
                'code_alpha_3' => 'UGA',
                'code_numeric' => '800',
                'name' => 'Uganda',
            ],
            [
                'code_alpha_2' => 'UM',
                'code_alpha_3' => 'UMI',
                'code_numeric' => '581',
                'name' => 'United States Minor Outlying Islands',
            ],
            [
                'code_alpha_2' => 'US',
                'code_alpha_3' => 'USA',
                'code_numeric' => '840',
                'name' => 'United States of America',
            ],
            [
                'code_alpha_2' => 'UY',
                'code_alpha_3' => 'URY',
                'code_numeric' => '858',
                'name' => 'Uruguay',
            ],
            [
                'code_alpha_2' => 'UZ',
                'code_alpha_3' => 'UZB',
                'code_numeric' => '860',
                'name' => 'Uzbekistan',
            ],
            [
                'code_alpha_2' => 'VE',
                'code_alpha_3' => 'VEN',
                'code_numeric' => '862',
                'name' => 'Venezuela',
            ],
            [
                'code_alpha_2' => 'VG',
                'code_alpha_3' => 'VGB',
                'code_numeric' => '92',
                'name' => 'Virgin Islands - British',
            ],
            [
                'code_alpha_2' => 'VI',
                'code_alpha_3' => 'VIR',
                'code_numeric' => '850',
                'name' => 'Virgin Islands - U.S.',
            ],
            [
                'code_alpha_2' => 'VU',
                'code_alpha_3' => 'VUT',
                'code_numeric' => '548',
                'name' => 'Vanuatu',
            ],
            [
                'code_alpha_2' => 'VN',
                'code_alpha_3' => 'VNM',
                'code_numeric' => '704',
                'name' => 'Viet Nam',
            ],
            [
                'code_alpha_2' => 'WF',
                'code_alpha_3' => 'WLF',
                'code_numeric' => '876',
                'name' => 'Wallis and Futuna',
            ],
            [
                'code_alpha_2' => 'YE',
                'code_alpha_3' => 'YEM',
                'code_numeric' => '887',
                'name' => 'Yemen',
            ],
            [
                'code_alpha_2' => 'ZM',
                'code_alpha_3' => 'ZMB',
                'code_numeric' => '894',
                'name' => 'Zambia',
            ],
            [
                'code_alpha_2' => 'ZW',
                'code_alpha_3' => 'ZWE',
                'code_numeric' => '716',
                'name' => 'Zimbabwe',
            ],
        ];
    }
}
